GET_SETTINGS = "settings/get"
MANUAL_MOVE_TOPIC = "robot/control/manual"

# NEW
UPDATE_SETTINGS = "settings/update"
LOGIN = "login"
QR_LOGIN = "camera/login"

START = "start"
STOP = "stop"
START_CONTOUR_DETECTION = "START_CONTOUR_DETECTION"
STOP_CONTOUR_DETECTION = "STOP_CONTOUR_DETECTION"
CALIBRATE = "calibrate"
CALIBRATE_CAMERA = "calibrate_camera"
CALIBRATE_ROBOT = "calibrate_robot"
CAPTURE_CALIBRATION_IMAGE = "capture_calibration_image"
HOME_ROBOT = "home_robot"
GO_TO_CALIBRATION_POS = "GO_to_calibration_pos"
GO_TO_LOGIN_POS = "got_to_login_pos"
JOG_ROBOT = "jog_robot"
SAVE_WORKPIECE = "save_workpiece"
SAVE_WORKPIECE_DXF = "save_workpiece_dxf"
TEST_CALIBRATION = "test_calibration"
SAVE_WORK_AREA_POINTS = "save_work_area_points"
WORPIECE_GET_ALL = "WORKPIECE_GET_ALL"
UPDATE_CAMERA_FEED = "cameraFeed/update"
CREATE_WORKPIECE_TOPIC = "CREATE_WORKPIECE_TOPIC"
SAVE_ROBOT_CALIBRATION_POINT = "SAVE_ROBOT_CALIBRATION_POINT"
HELP = "HELP"
RAW_MODE_ON = "rawModeOn"
RAW_MODE_OFF = "rawModeOff"

TEST_RUN = "test_run"